### ISSUE TITLE
Other visualization software

### ISSUE THREAD

**Issue by bkmgit** [carpentries-incubator/intro-data-viz#33]
Might other software for producing visualizations be considered?
Examples include:
- [LibreOffice](https://www.libreoffice.org/)
- [OnlyOffice](https://www.onlyoffice.com/)
- [Binder](https://mybinder.org/)

**Comment by jbkieffer** [comment]
Yes, the visualizations in this lesson are basic by design, so they could be taught with any spreadsheet-style program. We chose to start lesson development with Google Sheets for several reasons:

- Software access (e.g. Excel) and installation (e.g. any desktop application) can be barriers
- Because the material is very introductory, we wanted instructors and learners to be able to focus on concepts rather than tools
- We wanted the instructor(s) and helper(s) to be able to teach using one platform only. When learners are using a mix of software, it gets challenging very quickly to troubleshoot and to keep cognitive load low.

We do recognize that Google Sheets doesn't meet these goals for everyone, though. I'm not familiar with running a spreadsheet program on Binder, but if there's a way to do so that meets the lesson's goals of introducing data visualization with as few software barriers as possible, it would be interesting to learn more. And, as with any Carpentries-style lesson, the instructor is free to adapt the lesson as they see fit.
